/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 *// writing to register directly 


#include "stdint.h"
#define RCC_BASE 			0x40021000
#define PORT_A_BASE 		0x40010800
#define RCC_APB2ENR 		*(volatile uint32_t*)(RCC_BASE		+0x18)
#define GPIO_CRH 			*(volatile uint32_t*)(PORT_A_BASE	+0x04)
#define GPIO_ODR 			*(volatile uint32_t*)(PORT_A_BASE	+0x0C)
#define RCC_IOPAEN			(1<<2)
#define GPIOA13 			(1UL<<13)


int main(void)
{

	RCC_APB2ENR |= RCC_IOPAEN; // set enbale
	GPIO_CRH &= 0xff0fffff; // clear  half byte / short from bit 20 -> 24 with register remains
						    //untouched
	GPIO_CRH |= 0x00200000; // set 	  half byte / short from bit 20-> 24
	while (1)
	{

		GPIO_ODR |= GPIOA13; // set bit to 1
		for(int i=0;i<5000;i++);
		GPIO_ODR &= ~GPIOA13;
		for(int i=0;i<5000;i++);

	}

	return 0;
}
